version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - sqlite_data:/app/data
    environment:
      - PORT=5000
      - NODE_ENV=production
      - DATABASE_URL=file:/app/data/todo.db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Use relative endpoint. Nginx will reverse proxy '/api' to backend container
        - VITE_API_URL=/api/v1
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  sqlite_data:
    name: srt_todo_sqlite_data
